dist: trusty
sudo: required

language: php

cache:
  directories:
  - "$HOME/.composer/cache/files"

env:
  global:
    - COMPOSE_FILE="doc/docker/base-dev.yml:doc/docker/selenium.yml"
    - APP_ENV=behat
    - APP_DEBUG=1
    - PROJECT_VERSION=^3.3.x-dev

matrix:
  fast_finish: true
  include:
  - name: ""
    php: 7.3
    env:
      - BEHAT_OPTS="--profile=browser --suite=password -c=behat_ibexa_oss.yaml"
  - name: "User login providers tests"
    php: 7.3
    env:
      - SETUP_BEHAT_OPTS="--mode=standard --profile=setup --suite=login-methods -c=behat_ibexa_oss.yaml"
      - BEHAT_OPTS="--profile=browser --suite=providers -c=behat_ibexa_oss.yaml"

branches:
  only:
  - master
  - /^\d.\d+$/

before_install:
- echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- TEST_TIMEZONES=("America/New_York" "Asia/Calcutta" "UTC")
- TEST_TIMEZONE=${TEST_TIMEZONES["`shuf -i 0-2 -n 1`"]}

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest
  - ./vendor/bin/prepare_project_edition.sh oss ${PROJECT_VERSION} ${COMPOSE_FILE}

before_script:
  - if [ "${SETUP_BEHAT_OPTS}" != "" ] ; then cd "$HOME/build/project"; docker-compose exec --user www-data app sh -c "vendor/bin/ezbehat $SETUP_BEHAT_OPTS" ; fi

script:
  - cd "$HOME/build/project"; docker-compose exec --user www-data app sh -c "vendor/bin/ezbehat ${BEHAT_OPTS}"

after_script:
  - vendor/bin/ezreport

notifications:
  slack:
    rooms:
      - secure: EaR+jN0IrmT71U6ahNLepHApB3A6PXlPwK+hwaMcId1c1IuwcalACMYNIqjIQr0cvHpTH7PGM2TtR648i9hRn+CrGDZZU6448T5Vh72E+1KiZ79rXByHr/a27onp5Lx5NSKlSila/bjWT+qsvJ/fUy+RLK42vVVCUrdbE2hvwLoOvUtiaPVyJU+TXzq9uIERoS+lknwVP/HMbXQ8k3h25GVD4MgYHZZ3mk1s62mef+EUwdXi11CoHsCoU4+equTyXv6W2xir7JWjgegTsoCepr+kL4U5hJt9zugi6Q+S8gHBCTQd3d+tgNq/Hbyp3cYh/ewldpSiO8otLUj94Z+8r9GNiMITkAf/Hv1srY4pBsKXKWYkrkWJdOKsvaSIiRkDiwdBe+ZFg7td/HsUsbtGBmzYcn7RLbx1zy6kTQz/qZShqgBMiaDx10f4N0O53x4B5n6PlvjiM6OixPjzlAqF/4WLhzp0hYn7aHvCalb867J7vLnc1+chYpvidAuj10xhoY1ndviCVT8aCm0Vt6yzQe+3Qu5/Zq6Zgmv8IfxTDdCtouBqZJ83OpzZw9gReFdZvx/+7/PFcLPNqCp7v104z9M7EFSn/ZFuy1XmFF5H3bGNRYRiSVDYwdisrQnMXNbUYjpqoYGB7fqYvB5JwXwhT7VBvUy4LptvCkMjLDLUF2o=
    on_success: change
    on_failure: always
    on_pull_requests: false

git:
  depth: 30
