#
# Profile
#

ezplatform.user_profile.change_password:
    path: /user/change-password
    defaults:
        _controller: 'EzSystems\EzPlatformUserBundle\Controller\PasswordChangeController::userPasswordChangeAction'

ezplatform.user.forgot_password:
    path: /user/forgot-password
    defaults:
        _controller: 'EzSystems\EzPlatformUserBundle\Controller\PasswordResetController::userForgotPasswordAction'

ezplatform.user.forgot_password.login:
    path: /user/forgot-password/login
    defaults:
        _controller: 'EzSystems\EzPlatformUserBundle\Controller\PasswordResetController::userForgotPasswordLoginAction'

ezplatform.user.reset_password:
    path: /user/reset-password/{hashKey}
    defaults:
        _controller: 'EzSystems\EzPlatformUserBundle\Controller\PasswordResetController::userResetPasswordAction'

# Deprecated in v2.5 and will be removed in v3.0. Use ezplatform.user.register instead.
ez_user_register:
    path: /register
    defaults:
        _controller: 'EzSystems\EzPlatformUserBundle\Controller\UserRegisterController::registerAction'

# Deprecated in v2.5 and will be removed in v3.0. Use ezplatform.user.register_confirmation instead.
ez_user_register_confirmation:
    path: /register-confirm
    defaults:
        _controller: 'EzSystems\EzPlatformUserBundle\Controller\UserRegisterController::registerConfirmAction'

ezplatform.user.register: &user_register
    path: /register
    defaults:
        _controller: 'EzSystems\EzPlatformUserBundle\Controller\UserRegisterController::registerAction'

ezplatform.user.user_register:
    <<: *user_register
    path: /user/register

ezplatform.user.register_confirmation: &user_register_confirmation
    path: /register-confirm
    defaults:
        _controller: 'EzSystems\EzPlatformUserBundle\Controller\UserRegisterController::registerConfirmAction'

ezplatform.user.user_register_confirmation:
    <<: *user_register_confirmation
    path: /user/register-confirm

ezplatform.user_settings.list:
    path: /user/settings/list/{page}
    defaults:
        _controller: 'EzSystems\EzPlatformUserBundle\Controller\UserSettingsController::listAction'
        page: 1
    requirements:
        page: \d+

ezplatform.user_settings.update:
    path: /user/settings/update/{identifier}
    defaults:
        _controller: 'EzSystems\EzPlatformUserBundle\Controller\UserSettingsController::updateAction'
    requirements:
        identifier: .+
