imports:
    - { resource: services/controllers.yml }
    - { resource: services/validators.yml }
    - { resource: services/user_settings.yml }
    - { resource: services/forms.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformUser\EventListener\:
        resource: "../../../lib/EventListener/*"
        public: true
        tags:
            - { name: kernel.event_subscriber }

    EzSystems\RepositoryForms\EventListener\ViewTemplatesListener:
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [setViewTemplate, ['EzSystems\EzPlatformUser\View\ChangePassword\FormView', "$user_change_password.templates.form$"]]
            - [setViewTemplate, ['EzSystems\EzPlatformUser\View\ChangePassword\SuccessView', "$user_change_password.templates.success$"]]
            - [setViewTemplate, ['EzSystems\EzPlatformUser\View\ForgotPassword\FormView', "$user_forgot_password.templates.form$"]]
            - [setViewTemplate, ['EzSystems\EzPlatformUser\View\ForgotPassword\SuccessView', "$user_forgot_password_success.templates.form$"]]
            - [setViewTemplate, ['EzSystems\EzPlatformUser\View\ForgotPassword\LoginView', "$user_forgot_password_login.templates.form$"]]
            - [setViewTemplate, ['EzSystems\EzPlatformUser\View\ResetPassword\FormView', "$user_reset_password.templates.form$"]]
            - [setViewTemplate, ['EzSystems\EzPlatformUser\View\ResetPassword\InvalidLinkView', "$user_reset_password.templates.invalid_link$"]]
            - [setViewTemplate, ['EzSystems\EzPlatformUser\View\ResetPassword\SuccessView', "$user_reset_password.templates.success$"]]
            - [setViewTemplate, ['EzSystems\EzPlatformUser\View\UserSettings\ListView', "$user_settings.templates.list$"]]
            - [setViewTemplate, ['EzSystems\EzPlatformUser\View\Register\FormView', "$user_registration.templates.form$"]]
            - [setViewTemplate, ['EzSystems\EzPlatformUser\View\Register\ConfirmView', "$user_registration.templates.confirmation$"]]
            - [setPagelayout, ["$pagelayout$"]]

    EzSystems\EzPlatformUser\ConfigResolver\ConfigurableRegistrationGroupLoader:
        calls:
            - [setParam, ["groupId", "$user_registration.group_id$"]]

    EzSystems\EzPlatformUser\ConfigResolver\ConfigurableRegistrationContentTypeLoader:
        calls:
            - [setParam, ["contentTypeIdentifier", "%ezrepoforms.user_content_type_identifier%"]]

    EzSystems\EzPlatformUser\Form\DataMapper\UserRegisterMapper:
        calls:
            - [setParam, ["language", "@=service('ezpublish.config.resolver').getParameter('languages', null, null)[0]"]]

    EzSystems\EzPlatformUser\Form\Processor\UserRegisterFormProcessor:
        tags:
            - { name: kernel.event_subscriber }

    EzSystems\EzPlatformUser\Templating\Twig\DateTimeExtension:
        tags:
            - { name: twig.extension }
