services:

    EzSystems\EzPlatformUserBundle\Controller\:
        resource: "../../Controller/*"
        exclude: "../../Controller/{Controller}"
        parent: EzSystems\EzPlatformUserBundle\Controller\Controller

    EzSystems\EzPlatformUserBundle\Controller\Controller:
        calls:
            - [setContainer, ["@service_container"]]
            - [performAccessCheck, []]
        tags: [controller.service_arguments]

    EzSystems\EzPlatformUserBundle\Controller\PasswordResetController:
        autowire: true
        arguments:
            $actionResultHandler: '@EzSystems\EzPlatformUser\ExceptionHandler\NullActionResultHandler'
        calls:
            - [setContainer, ['@service_container']]
        tags: [controller.service_arguments]

    EzSystems\EzPlatformUserBundle\Controller\PasswordChangeController:
        autowire: true
        arguments:
            $siteAccessGroups: '%ezpublish.siteaccess.groups%'
        calls:
            - [setContainer, ['@service_container']]
            - [performAccessCheck, []]
        tags: [controller.service_arguments]

    EzSystems\EzPlatformUserBundle\Controller\UserRegisterController:
        autowire: true
        arguments:
            $userActionDispatcher: '@ezplatform.content_forms.action_dispatcher.user'
        tags: [controller.service_arguments]

    EzSystems\EzPlatformUserBundle\Controller\UserSettingsController:
        autowire: true
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags: [controller.service_arguments]
