services:

    EzSystems\EzPlatformUserBundle\Controller\:
        resource: "../../Controller/*"
        exclude: "../../Controller/{Controller}"
        parent: EzSystems\EzPlatformUserBundle\Controller\Controller

    EzSystems\EzPlatformUserBundle\Controller\Controller:
        tags: [controller.service_arguments]
        calls:
            - [setContainer, ["@service_container"]]
            - [performAccessCheck, []]

    EzSystems\EzPlatformUserBundle\Controller\PasswordResetController:
        tags: [controller.service_arguments]
        autowire: true
        calls:
            - [setContainer, ['@service_container']]
        arguments:
            $tokenIntervalSpec: '$security.token_interval_spec$'
            $forgotPasswordMail: '$user_forgot_password.templates.mail$'
            $senderAddress: "@=container.hasParameter('swiftmailer.sender_address') ? parameter('swiftmailer.sender_address') : ''"

    EzSystems\EzPlatformUserBundle\Controller\PasswordChangeController:
        autowire: true
        arguments:
            $siteAccessGroups: '%ezpublish.siteaccess.groups%'
        calls:
            - [setContainer, ['@service_container']]
            - [performAccessCheck, []]

    EzSystems\EzPlatformUserBundle\Controller\UserRegisterController:
        autowire: true
        arguments:
            $userActionDispatcher: '@ezrepoforms.action_dispatcher.user'

    EzSystems\EzPlatformUserBundle\Controller\UserSettingsController:
        parent: EzSystems\EzPlatformAdminUiBundle\Controller\Controller
        arguments:
            $defaultPaginationLimit: '$pagination_user.user_settings_limit$'
