services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformUser\Form\Type\:
        resource: "../../../lib/Form/Type/*"

    EzSystems\EzPlatformUser\Form\Factory\FormFactory: ~

    EzSystems\EzPlatformUser\Form\ChoiceList\Loader\AvailableLocaleChoiceLoader:
        arguments:
            $availableTranslations: '%available_translations%'

    EzSystems\EzPlatformUser\Form\Type\UserSettings\FullDateTimeFormatType: ~

    EzSystems\EzPlatformUser\Form\Type\UserSettings\ShortDateTimeFormatType: ~
